module R2OAS
  module Schema
    class PathItemFileManager
      @manager: untyped

      extend Forwardable

      def initialize: (untyped path, ?::Symbol path_type) -> void

      alias self.build self.new
    end
  end
end
