# Scope Rails
module R2OAS
  module Schema
    module V3
      class ComponentsAnalyzer < BaseAnalyzer
        @options: untyped

        def initialize: (untyped before_schema_data, untyped after_schema_data, ?::Hash[untyped, untyped] options) -> void

        def analyze_docs: () -> untyped
      end
    end
  end
end
