module R2OAS
  module Schema
    module V3
      class PathGenerator < BaseGenerator
        @paths: untyped

        @glob_schema_paths: untyped

        def initialize: (?::Hash[untyped, untyped] schema_data, ?::Hash[untyped, untyped] options) -> void

        def generate_docs: () -> untyped

        private

        alias paths_files_paths schema_files_paths

        def generate_docs_from_routes_data: () -> untyped

        def process_when_generate_docs: () ?{ (untyped) -> untyped } -> untyped

        def create_glob_paths_paths: () -> (untyped | ::Array[::String])

        def unit_paths_data_group_by_tags: (untyped unit_paths_data) -> untyped

        def save_each_tags: (untyped unit_paths_data) ?{ (untyped) -> untyped } -> untyped
      end
    end
  end
end
