module R2OAS
  module Schema
    module V3
      class PathItemFileManager < IncludeRefBaseFileManager
        @recursive_search_class: untyped

        def initialize: (untyped path, ?::Symbol path_type) -> void

        def skip_save?: () -> untyped
      end
    end
  end
end
