# Scope Rails
module R2OAS
  module Schema
    module V3
      class Base < ::R2OAS::Schema::Base
        SUPPORT_COMPONENTS_OBJECTS: ::Array["schemas" | "requestBodies" | "securitySchemes" | "parameters" | "responses" | "examples" | "headers" | "links" | "callbacks"]

        def support_components_objects: () -> untyped
      end
    end
  end
end
