module R2OAS
  module Schema
    module V3
      class Generator < BaseGenerator
        @doc_generator: untyped

        extend Forwardable

        def initialize: (?::Hash[untyped, untyped] options) -> void
      end
    end
  end
end
