# frozen_string_literal: true

require 'spec_helper'
require 'open3'

RSpec.describe 'Jekyll SEO Optimization and Metadata' do
  let(:docs_root) { File.expand_path('../docs', __dir__) }
  let(:site_dir) { File.join(docs_root, '_site') }
  let(:build_script) { File.expand_path('../devscript/build_docs.sh', __dir__) }

  before(:all) do
    # Ensure site is built with SEO plugins active
    # This verifies jekyll-seo-tag and jekyll-sitemap plugins work correctly
    build_script_path = File.expand_path('../devscript/build_docs.sh', __dir__)
    Open3.capture3('/bin/bash', build_script_path)
  end

  describe 'SEO meta tags (Task 8.1)' do
    context 'jekyll-seo-tag plugin functionality' do
      it 'generates meta tags in HTML pages' do
        index_html = File.join(site_dir, 'index.html')

        expect(File.exist?(index_html)).to be true

        content = File.read(index_html)

        # Should have meta tags generated by jekyll-seo-tag
        expect(content).to match(/<meta.*name="generator".*content="Jekyll.*"/)
      end

      it 'includes canonical URL meta tag' do
        index_html = File.join(site_dir, 'index.html')
        content = File.read(index_html)

        # Canonical URL should be set
        expect(content).to match(/<link rel="canonical" href="[^"]+"/)
      end

      it 'includes description meta tag' do
        index_html = File.join(site_dir, 'index.html')
        content = File.read(index_html)

        # Should have description meta tag
        expect(content).to match(/<meta.*name="description".*content="[^"]+"/)
      end

      it 'includes title tag properly formatted' do
        index_html = File.join(site_dir, 'index.html')
        content = File.read(index_html)

        # Should have proper title tag
        expect(content).to match(/<title>[^<]+<\/title>/)
      end
    end

    context 'Open Graph meta tags' do
      it 'includes Open Graph type meta tag' do
        index_html = File.join(site_dir, 'index.html')
        content = File.read(index_html)

        # Open Graph type
        expect(content).to match(/<meta property="og:type" content="[^"]+"/)
      end

      it 'includes Open Graph title meta tag' do
        index_html = File.join(site_dir, 'index.html')
        content = File.read(index_html)

        # Open Graph title
        expect(content).to match(/<meta property="og:title" content="[^"]+"/)
      end

      it 'includes Open Graph URL meta tag' do
        index_html = File.join(site_dir, 'index.html')
        content = File.read(index_html)

        # Open Graph URL
        expect(content).to match(/<meta property="og:url" content="[^"]+"/)
      end

      it 'includes Open Graph site_name meta tag' do
        index_html = File.join(site_dir, 'index.html')
        content = File.read(index_html)

        # Open Graph site name
        expect(content).to match(/<meta property="og:site_name" content="[^"]+"/)
      end

      it 'includes Open Graph description meta tag' do
        index_html = File.join(site_dir, 'index.html')
        content = File.read(index_html)

        # Open Graph description
        expect(content).to match(/<meta property="og:description" content="[^"]+"/)
      end
    end

    context 'Twitter Card meta tags' do
      it 'includes Twitter card type meta tag' do
        index_html = File.join(site_dir, 'index.html')
        content = File.read(index_html)

        # Twitter card type
        expect(content).to match(/<meta.*name="twitter:card".*content="summary"/)
      end

      it 'includes Twitter title meta tag' do
        index_html = File.join(site_dir, 'index.html')
        content = File.read(index_html)

        # Twitter title
        expect(content).to match(/<meta property="twitter:title" content="[^"]+"/)
      end
    end

    context 'meta tags on content pages' do
      it 'includes SEO meta tags on usage pages' do
        usage_page = File.join(site_dir, 'usage', 'initialize', 'index.html')

        if File.exist?(usage_page)
          content = File.read(usage_page)

          # Should have meta description
          expect(content).to match(/<meta.*name="description"/)
          # Should have Open Graph tags
          expect(content).to match(/<meta property="og:/)
        end
      end

      it 'includes SEO meta tags on configuration pages' do
        config_page = File.join(site_dir, 'configuration', 'index.html')

        if File.exist?(config_page)
          content = File.read(config_page)

          # Should have meta description
          expect(content).to match(/<meta.*name="description"/)
          # Should have Open Graph tags
          expect(content).to match(/<meta property="og:/)
        end
      end

      it 'includes canonical URLs on all pages' do
        html_files = Dir.glob(File.join(site_dir, '**', 'index.html'))

        html_files.each do |html_file|
          content = File.read(html_file)

          # Every page should have canonical URL
          expect(content).to match(/<link rel="canonical" href="[^"]+"/)
        end
      end
    end
  end

  describe 'Sitemap and robots.txt (Task 8.2)' do
    context 'sitemap.xml generation' do
      it 'generates sitemap.xml file' do
        sitemap_path = File.join(site_dir, 'sitemap.xml')

        expect(File.exist?(sitemap_path)).to be true
      end

      it 'includes valid XML structure in sitemap' do
        sitemap_path = File.join(site_dir, 'sitemap.xml')

        if File.exist?(sitemap_path)
          content = File.read(sitemap_path)

          # Should have XML declaration
          expect(content).to match(/<?xml version="1.0"/)
          # Should have urlset element
          expect(content).to match(/<urlset/)
          # Should have xmlns attribute
          expect(content).to match(/xmlns="http:\/\/www\.sitemaps\.org\/schemas\/sitemap\/0\.9"/)
        end
      end

      it 'includes index page in sitemap' do
        sitemap_path = File.join(site_dir, 'sitemap.xml')

        if File.exist?(sitemap_path)
          content = File.read(sitemap_path)

          # Should include home page URL
          expect(content).to include('<loc>')
          expect(content).to match(/<loc>.*\/r2-oas\/<\/loc>/)
        end
      end

      it 'includes documentation pages in sitemap' do
        sitemap_path = File.join(site_dir, 'sitemap.xml')

        if File.exist?(sitemap_path)
          content = File.read(sitemap_path)

          # Should include usage pages
          expect(content).to match(/<loc>.*\/usage\/.*<\/loc>/)
          # Should include configuration pages
          expect(content).to match(/<loc>.*\/configuration\/.*<\/loc>/)
        end
      end

      it 'includes URL entries for all documentation pages' do
        sitemap_path = File.join(site_dir, 'sitemap.xml')

        if File.exist?(sitemap_path)
          content = File.read(sitemap_path)

          # Should have multiple URL entries
          url_count = content.scan(/<url>/).length
          expect(url_count).to be > 20 # We have at least 21+ pages
        end
      end
    end

    context 'robots.txt file' do
      it 'has robots.txt file in site root' do
        robots_path = File.join(site_dir, 'robots.txt')

        expect(File.exist?(robots_path)).to be true
      end

      it 'allows all crawlers by default' do
        robots_path = File.join(site_dir, 'robots.txt')

        if File.exist?(robots_path)
          content = File.read(robots_path)

          # Should have User-agent: *
          expect(content).to match(/User-agent:\s*\*/)
        end
      end

      it 'includes sitemap location' do
        robots_path = File.join(site_dir, 'robots.txt')

        if File.exist?(robots_path)
          content = File.read(robots_path)

          # Should reference sitemap.xml
          expect(content).to match(/Sitemap:\s*http/)
          expect(content).to include('sitemap.xml')
        end
      end

      it 'has proper format for crawl directives' do
        robots_path = File.join(site_dir, 'robots.txt')

        if File.exist?(robots_path)
          content = File.read(robots_path)

          # Should have either Allow or Disallow directive
          expect(content).to match(/Allow:|Disallow:/)
        end
      end
    end

    context 'sitemap accessibility' do
      it 'places sitemap.xml at site root for easy discovery' do
        sitemap_path = File.join(site_dir, 'sitemap.xml')

        # Sitemap should be at root, not in subdirectory
        expect(File.exist?(sitemap_path)).to be true
        expect(sitemap_path).to end_with('_site/sitemap.xml')
      end

      it 'makes sitemap accessible via robots.txt reference' do
        robots_path = File.join(site_dir, 'robots.txt')
        sitemap_path = File.join(site_dir, 'sitemap.xml')

        if File.exist?(robots_path) && File.exist?(sitemap_path)
          robots_content = File.read(robots_path)

          # Robots.txt should point to sitemap
          expect(robots_content).to include('sitemap.xml')
        end
      end
    end
  end

  describe 'SEO plugin configuration' do
    context '_config.yml settings' do
      let(:config_file) { File.join(docs_root, '_config.yml') }

      it 'includes jekyll-seo-tag in plugins' do
        content = File.read(config_file)

        expect(content).to match(/jekyll-seo-tag/)
      end

      it 'includes jekyll-sitemap in plugins' do
        content = File.read(config_file)

        expect(content).to match(/jekyll-sitemap/)
      end

      it 'has site title configured for SEO' do
        content = File.read(config_file)

        expect(content).to match(/^title:\s*.+/)
      end

      it 'has site description configured for SEO' do
        content = File.read(config_file)

        expect(content).to match(/^description:\s*.+/)
      end

      it 'has site URL configured for SEO' do
        content = File.read(config_file)

        expect(content).to match(/^url:\s*"?http/)
      end

      it 'has baseurl configured for GitHub Pages' do
        content = File.read(config_file)

        expect(content).to match(/^baseurl:\s*"?\/r2-oas"?/)
      end
    end
  end
end
