module R2OAS
  module AppConfiguration
    class Deprecation
      @silenced: untyped

      DEFAULT_SILENCED: untyped

      attr_reader silenced: untyped

      def silenced=: (untyped value) -> untyped

      def initialize: () -> void

      private

      def set_default: () -> untyped
    end
  end
end

module R2OAS
  module AppConfiguration
    class Server
      DEFAULT_URL: "http://localhost:3000"

      DEFAULT_DESCRIPTION: "localhost"

      VALID_OPTIONS_KEYS: ::Array[:data]

      def initialize: () -> void

      def configure: () { (untyped) -> untyped } -> untyped

      private

      def set_default: () -> untyped
    end
  end
end

module R2OAS
  module AppConfiguration
    class Swagger
      class Editor
        DEFAULT_IMAGE: "swaggerapi/swagger-editor"

        DEFAULT_PORT: "81"

        DEFAULT_EXPOSED_PORT: "8080/tcp"

        DEFAULT_STORAGE_KEY: "swagger-editor-content"

        DEFAULT_HOST: "http://localhost"

        VALID_OPTIONS_KEYS: ::Array[:image | :port | :exposed_port]

        def initialize: () -> void

        def configure: () { (untyped) -> untyped } -> untyped

        def url: () -> ::String

        def storage_key: () -> untyped

        private

        def set_default: () -> untyped
      end
    end
  end
end

module R2OAS
  module AppConfiguration
    class Swagger
      class UI
        DEFAULT_IMAGE: "swaggerapi/swagger-ui"

        DEFAULT_PORT: "8080"

        DEFAULT_EXPOSED_PORT: "8080/tcp"

        DEFAULT_VOLUME: "/app/swagger.json"

        DEFAULT_HOST: "http://localhost"

        VALID_OPTIONS_KEYS: ::Array[:image | :port | :exposed_port | :volume]

        def initialize: () -> void

        def configure: () { (untyped) -> untyped } -> untyped

        def url: () -> ::String

        private

        def set_default: () -> untyped
      end
    end
  end
end

module R2OAS
  module AppConfiguration
    class Swagger
      DEFAULT_EDITOR: untyped

      DEFAULT_UI: untyped

      VALID_OPTIONS_KEYS: ::Array[:editor | :ui]

      def initialize: () -> void

      def configure: () { (untyped) -> untyped } -> untyped

      private

      def set_default: () -> untyped
    end
  end
end

module R2OAS
  module AppConfiguration
    DEFAULT_VERSION: :v3

    DEFAULT_ROOT_DIR_PATH: "./oas_docs"

    DEFAULT_SCHEMA_SAVE_DIR_NAME: "src"

    DEFAULT_DOC_SAVE_FILE_NAME: "oas_doc.yml"

    DEFAULT_FORCE_UPDATE_SCHEMA: false

    DEFAULT_USE_TAG_NAMESPACE: true

    DEFAULT_USE_SCHEMA_NAMESPACE: true

    DEFAULT_SERVER: untyped

    DEFAULT_INTERVAL_TO_SAVE_EDITED_TMP_SCHEMA: ::Float

    DEFAULT_SWAGGER: untyped

    # rubocop:disable Style/MutableConstant
    DEFAULT_HTTP_STATUSES_WHEN_HTTP_METHOD: { get: { default: ::Array["200" | "422"], path_parameter: ::Array["200" | "404" | "422"] }, post: { default: ::Array["201" | "422"], path_parameter: ::Array["201" | "404" | "422"] }, patch: { default: ::Array["204" | "422"], path_parameter: ::Array["204" | "404" | "422"] }, put: { default: ::Array["204" | "422"], path_parameter: ::Array["204" | "404" | "422"] }, delete: { default: ::Array["200" | "422"], path_parameter: ::Array["200" | "404" | "422"] } }

    DEFAULT_HTTP_METHODS_WHEN_GENERATE_REQUEST_BODY: ::Array["post" | "patch" | "put"]

    DEFAULT_IGNORED_HTTP_STATUSES_WHEN_GENERATE_COMPONENT_SCHEMA: ::Array["204" | "404"]

    # rubocop:enable Style/MutableConstant
    # :dot or :underbar
    DEFAULT_NAMESPACE_TYPE: :dot

    DEFAULT_DEPLOY_DIR_PATH: "./deploy_docs"

    EDFAULT_PLUGINS: ::Array[untyped]

    DEFAULT_LOCAL_PLUGINS_DIR_NAME: "plugins"

    DEFAULT_LOCAL_TASKS_DIR_NAME: "tasks"

    DEFAULT_OUTPUT_PATH: "./oas_docs/dist/oas_doc.yml"

    DEFAULT_DEPRECATION: untyped

    PUBLIC_VALID_OPTIONS_KEYS: ::Array[:version | :root_dir_path | :schema_save_dir_name | :doc_save_file_name | :force_update_schema | :use_tag_namespace | :use_schema_namespace | :server | :interval_to_save_edited_tmp_schema | :swagger | :http_statuses_when_http_method | :http_methods_when_generate_request_body | :ignored_http_statuses_when_generate_component_schema | :namespace_type | :deploy_dir_path | :plugins | :local_plugins_dir_name | :local_tasks_dir_name | :output_path | :deprecation]

    UNPUBLIC_VALID_OPTIONS_KEYS: ::Array[:paths_config | :logger]

    VALID_OPTIONS_KEYS: untyped

    def options: () -> untyped

    private

    def self?.set_default: (untyped target) -> untyped
  end
end

module R2OAS
  class Base
    @options: untyped

    def initialize: (?::Hash[untyped, untyped] options) -> void

    private

    def merged_options: () -> untyped

    def logger: () -> untyped

    def schema_save_dir_path: () -> untyped

    def doc_save_file_path: () -> untyped

    def ns_div: () -> untyped
  end
end

module R2OAS
  module Configuration
    class PathsConfig
      @root_dir_path: untyped

      @schema_save_dir_path: untyped

      @many_paths_file_paths: untyped

      @many_components_file_paths: untyped

      include Helpers::FileHelper

      def initialize: (untyped root_dir_path, untyped schema_save_dir_name) -> void

      def abs_paths_path: () -> untyped

      def all_load_paths?: () -> untyped

      def many_paths_file_paths: () -> untyped

      def create_dot_paths: (?bool silent) -> untyped

      def many_components_file_paths: () -> untyped
    end
  end
end

module R2OAS
  module Configuration
    @_stdout_logger: untyped

    @_paths_config: untyped

    extend AppConfiguration

    include Helpers::FileHelper

    PUBLIC_VALID_OPTIONS_KEYS: untyped

    UNPUBLIC_VALID_OPTIONS_KEYS: ::Array[:paths_config | :logger]

    VALID_OPTIONS_KEYS: untyped

    def self.extended: (untyped base) -> untyped

    def configure: () ?{ (untyped) -> untyped } -> untyped

    def options: () -> untyped

    def logger: () -> untyped

    def paths_config: () -> untyped

    def app_configuration_options: () -> untyped

    def load_tasks: () -> untyped

    def init: () -> untyped

    def output_dir_path: () -> untyped

    private

    def load_local_tasks: () -> untyped

    def load_local_plugins: () -> untyped

    def set_default_for_configuration: (untyped target) -> untyped
  end
end

# Scope Rails
module R2OAS
  module Deploy
    class Client < Schema::Base
      @download_dir: untyped

      @base_dir: untyped

      @tar_path: untyped

      @dist_path: untyped

      @schema_file_path: untyped

      # Get master branch tarball from GitHub API
      SWAGGER_UI_TARBALL_URL: "https://api.github.com/repos/swagger-api/swagger-ui/tarball/master"

      FALLBACK_DIST_PATH: untyped

      def initialize: (?::Hash[untyped, untyped] options) -> void

      def download_swagger_ui_dist: () -> (untyped | true)

      def deploy: () -> untyped

      private

      def copy_swagger_ui_dist: () -> untyped

      def copy_swagger_ui_index: () -> untyped

      def copy_oas_doc_file: () -> untyped

      def remove_download_dist: () -> untyped

      def make_index: (untyped template) -> untyped
    end
  end
end

# Background colors
# 40	Black
# 41	Red
# 42	Green
# 43	Yellow
# 44	Blue
# 45	Magenta
# 46	Cyan
# 47	White
module R2OAS
  module Helpers
    module FileHelper
      def write_file_or_skip: (untyped file_path, untyped data, ?bool silent) -> (untyped | nil)

      def mkdir_p_dir_or_skip: (untyped dir_path, ?bool silent) -> (untyped | nil)

      private

      def relative: (untyped path) -> untyped

      def bold: (untyped str) -> ::String

      def space: () -> "      "
    end
  end
end

module R2OAS
  module Hooks
    class GlobalHook
      attr_accessor callback: untyped

      attr_accessor once: untyped

      attr_accessor uid: untyped

      attr_accessor target: untyped

      def initialize: (untyped callback, untyped once, untyped uid, untyped target) -> void

      def call: (*untyped data) -> untyped
    end
  end
end

module R2OAS
  module Hooks
    class Hook
      self.@repository: untyped

      self.@type: untyped

      self.@hooks: untyped

      include Singleton

      attr_accessor self.repository: untyped

      def self.register: (untyped type, untyped target_class) -> self

      def self.on: (untyped on, untyped callback, untyped target_class, ?bool once) -> untyped

      #  MEMO: Do not Use
      def self.off: (untyped uid, untyped target_class) -> untyped

      def self.execute_hook: (untyped on, *untyped data, untyped target_class) -> untyped

      def self.has_hook?: (untyped name, untyped target_class) -> untyped

      private

      def self.execute_global_hook: (untyped on, *untyped data, untyped target_class) -> untyped

      def self.get_hook: (untyped name, untyped target_class) -> untyped
    end
  end
end

module R2OAS
  module Hooks
    class Repository
      @global_hooks_data: untyped

      @last_hook_id: untyped

      @target: untyped

      attr_accessor global_hooks_data: untyped

      attr_accessor last_hook_id: untyped

      attr_accessor target: untyped

      def initialize: (untyped target) -> void
    end
  end
end



# rubocop:disable all
class Hash
  # Returns a new hash with +self+ and +other_hash+ merged recursively.
  #
  #   h1 = { a: true, b: { c: [1, 2, 3] } }
  #   h2 = { a: false, b: { x: [3, 4, 5] } }
  #
  #   h1.deep_merge(h2) #=> { a: false, b: { c: [1, 2, 3], x: [3, 4, 5] } }
  #
  # Like with Hash#merge in the standard library, a block can be provided
  # to merge values:
  #
  #   h1 = { a: 100, b: 200, c: { c1: 100 } }
  #   h2 = { b: 250, c: { c1: 200 } }
  #   h1.deep_merge(h2) { |key, this_val, other_val| this_val + other_val }
  #   # => { a: 100, b: 450, c: { c1: 300 } }
  def deep_merge: (untyped other_hash) { (?) -> untyped } -> untyped

  # Same as +deep_merge+, but modifies +self+.
  def deep_merge!: (untyped other_hash) ?{ (?) -> untyped } -> self
end

# rubocop:disable all
class Object
  # An object is blank if it's false, empty, or a whitespace string.
  # For example, +false+, '', '   ', +nil+, [], and {} are all blank.
  #
  # This simplifies
  #
  #   !address || address.empty?
  #
  # to
  #
  #   address.blank?
  #
  # @return [true, false]
  def blank?: () -> untyped

  # An object is present if it's not blank.
  #
  # @return [true, false]
  def present?: () -> untyped

  # Returns the receiver if it's present otherwise returns +nil+.
  # <tt>object.presence</tt> is equivalent to
  #
  #    object.present? ? object : nil
  #
  # For example, something like
  #
  #   state   = params[:state]   if params[:state].present?
  #   country = params[:country] if params[:country].present?
  #   region  = state || country || 'US'
  #
  # becomes
  #
  #   region = params[:state].presence || params[:country].presence || 'US'
  #
  # @return [Object]
  def presence: () -> (self | nil)
end

class NilClass
  # +nil+ is blank:
  #
  #   nil.blank? # => true
  #
  # @return [true]
  def blank?: () -> true
end

class FalseClass
  # +false+ is blank:
  #
  #   false.blank? # => true
  #
  # @return [true]
  def blank?: () -> true
end

class TrueClass
  # +true+ is not blank:
  #
  #   true.blank? # => false
  #
  # @return [false]
  def blank?: () -> false
end

class Array
  # An array is blank if it's empty:
  #
  #   [].blank?      # => true
  #   [1,2,3].blank? # => false
  #
  # @return [true, false]
  alias blank? empty?
end

class Hash
  # A hash is blank if it's empty:
  #
  #   {}.blank?                # => true
  #   { key: 'value' }.blank?  # => false
  #
  # @return [true, false]
  alias blank? empty?
end

class String
  BLANK_REGEXP: ::Regexp

  # A string is blank if it's empty or contains whitespaces only:
  #
  #   ''.blank?       # => true
  #   '   '.blank?    # => true
  #   "\t\n\r".blank? # => true
  #   ' blah '.blank? # => false
  #
  # Unicode whitespace is supported:
  #
  #   "\u00a0".blank? # => true
  #
  # @return [true, false]
  def blank?: () -> untyped
end

class Numeric
  # No number is blank:
  #
  #   1.blank? # => false
  #   0.blank? # => false
  #
  # @return [false]
  def blank?: () -> false
end

class String
  # Returns the string, first removing all whitespace on both ends of
  # the string, and then changing remaining consecutive whitespace
  # groups into one space each.
  #
  # Note that it handles both ASCII and Unicode whitespace.
  #
  #   %{ Multi-line
  #      string }.squish                   # => "Multi-line string"
  #   " foo   bar    \n   \t   boo".squish # => "foo bar boo"
  def squish: () -> untyped

  # Performs a destructive squish. See String#squish.
  #   str = " foo   bar    \n   \t   boo"
  #   str.squish!                         # => "foo bar boo"
  #   str                                 # => "foo bar boo"
  def squish!: () -> self
end

# rubocop:disable all
module Twm
  #
  # orig: local docs
  # left: generate docs
  # right: local src files
  #
  # condition: merge right into left
  def self.yaml_merge: (untyped left, untyped orig, untyped right) -> untyped

  private

  def self.three_equal?: (untyped left, untyped orig, untyped right) -> ({ left_orig: true, orig_right: true, left_right: true } | { left_orig: true, orig_right: false, left_right: false } | { left_orig: false, orig_right: true, left_right: false } | { left_orig: false, orig_right: false, left_right: true } | { left_orig: false, orig_right: false, left_right: false } | nil)
end

module R2OAS
  module Plugin
    class Base < ::R2OAS::Base
      extend ::R2OAS::Plugin::Hookable

      attr_accessor self.plugin_name: untyped

      attr_accessor self.type: untyped

      attr_accessor self.opts: untyped

      def self.setup: () ?{ (?) -> untyped } -> (nil | untyped)

      def self.teardown: () ?{ (?) -> untyped } -> (nil | untyped)

      def self.execute_setup: (*untyped) -> untyped

      def self.execute_teardown: (*untyped) -> untyped

      def self.inherited: (untyped base) -> untyped
    end
  end
end

module R2OAS
  module Plugin
    class Executor
      self.@plugin_map: untyped

      self.@will_plugins: untyped

      @plugins: untyped

      @use_plugin: untyped

      @plugin_map: untyped

      extend ::R2OAS::Plugin::Hookable

      def initialize: (untyped plugins, untyped opts) -> void

      def execute_transform_plugins: (untyped hook_method, *untyped) -> (nil | untyped)

      attr_accessor self.plugin_map: untyped

      def self.execute_transform_plugins: (untyped plugin_map, untyped hook_method, *untyped) -> untyped

      def self.execute_plugins: (untyped plugin_map, untyped type, untyped hook_method, *untyped) -> (nil | untyped)

      # e.g.)
      # {
      #   transform: {
      #     setup: [
      #       { plugin_name: 'r2oas-transform-plugin-sample1', plugin_klass: Sample1Plugin, hook_method: :setup },
      #       { plugin_name: 'r2oas-transform-plugin-sample2', plugin_klass: Sample2Plugin, hook_method: :setup },
      #     ],
      #     info: [
      #       { plugin_name: 'r2oas-transform-plugin-sample1', plugin_klass: Sample1Plugin, hook_method: :info },
      #     ]
      #   }
      # }
      #
      def self.plugin_map: (untyped plugins) -> untyped

      def self.create_use_plugins_info: (untyped plugins) -> untyped
    end
  end
end

module R2OAS
  module Plugin
    module Hookable
      def self.extended: (untyped base) -> untyped

      def hooks_map: () -> untyped

      def hooks: () -> untyped

      def hook_klass=: (untyped klass) -> untyped

      def hook_klass: () -> untyped

      def on: (untyped on, untyped callback, ?bool once) -> untyped

      # MEMO: Do not Use
      def off: (untyped on, untyped callback, ?bool once) -> untyped

      def execute_hook: (untyped on, *untyped data) -> untyped

      def has_hook?: (untyped name) -> untyped
    end
  end
end



R2OAS::Plugin::Transform: untyped

module R2OAS
  module Plugin
    module V3
      class Transform < ::R2OAS::Plugin::Base
        extend Visitable

        def self.inherited: (untyped base) -> untyped
      end
    end
  end
end

module R2OAS
  module Plugin
    module V3
      module Visitable
        include R2OAS::Plugin::Hookable

        SCHEMA_OBJECTS: ::Array[:info | :path_item | :external_document | :components_schema | :components_request_body | :components_schema_name | :components_schema_name_at_request_body | :components_request_body_name]
      end
    end
  end
end



module R2OAS
  module Routing
    class Adjustor < Base
      @route_data: untyped

      @route: untyped

      @path_comp: untyped

      @request_comp: untyped

      @verb_comp: untyped

      @verbs: untyped

      VALID_KEYS: ::Array[:route | :name | :verb | :path | :reqs]

      def initialize: (untyped route_data) -> void

      def routes_els: () -> untyped

      private

      def valid_route_data?: (untyped route_data) -> (untyped | nil)
    end
  end
end

module R2OAS
  module Routing
    class Base < ::R2OAS::Base
    end
  end
end



module R2OAS
  module Routing
    class BaseComponent < Base
    end
  end
end

module R2OAS
  module Routing
    class PathComponent < BaseComponent
      @path: untyped

      FORMAT_PATH_PARAMETER_REGEXP: ::Regexp

      SYMBOL_PATH_PARAMETER_REGEXP: ::Regexp

      BRACE_PATH_PARAMETER_REGEXP: ::Regexp

      def initialize: (untyped path) -> void

      def to_s: () -> untyped

      def symbol_to_brace: () -> untyped

      def path_parameters_data: () -> (::Hash[untyped, untyped] | untyped)

      def path_excluded_path_parameters: () -> untyped

      def exist_path_parameters?: () -> untyped

      def path_parameters: () -> untyped

      private

      # e.x.) "/tasks(.:format)" => "/tasks"
      # e.x.) "/:model_name/:id/show_in_app(.:format)" => "/{model_name}/{id}/show_in_app"
      def without_format: () -> untyped
    end
  end
end

module R2OAS
  module Routing
    class RequestComponent < BaseComponent
      @request: untyped

      @is_route_engine: untyped

      def initialize: (untyped request, untyped is_route_engine) -> void

      # e.x.) "tasks#index" => "task"
      # e.x.) "RailsAdmin::Engine" => "rails_amin/engine"
      def to_tag_name: () -> untyped

      def to_schema_name: () -> untyped

      # e.x.) "tasks#index { :format => ":json" }"
      def to_format_name: () -> untyped

      private

      def adjust_namespace: (untyped namespace) -> untyped
    end
  end
end

module R2OAS
  module Routing
    class VerbComponent < BaseComponent
      @verb: untyped

      def initialize: (untyped verb) -> void

      # e.x.) "" => ["get"]
      # e.x.) "POST" => ["post"]
      # e.x.) "GET|POST" => ["get","post"]
      def verbs: () -> untyped
    end
  end
end

module R2OAS
  module Routing
    class Parser
      @_routes: untyped

      @_engines: untyped

      # routes should be Rails.application.routes.routes
      def initialize: (untyped routes) -> void

      def routes_data: () -> untyped

      def tags_data: () -> untyped

      def schemas_data: () -> untyped

      private

      attr_accessor _routes: untyped

      attr_accessor _engines: untyped

      def normalized_routes: () ?{ (?) -> untyped } -> untyped

      # copy from:
      # https://github.com/rails/rails/blob/v4.2.1/actionpack/lib/action_dispatch/routing/inspector.rb#L114-L140
      # https://github.com/rails/rails/blob/v5.2.3/actionpack/lib/action_dispatch/routing/inspector.rb
      def collect_routes: (untyped routes) -> untyped

      # copy from:
      # https://github.com/rails/rails/blob/v4.2.1/actionpack/lib/action_dispatch/routing/inspector.rb#L114-L140
      def collect_engine_routes: (untyped route) -> (nil | untyped)
    end
  end
end

module R2OAS
  module Schema
    class Analyzer
      @analyzer: untyped

      extend Forwardable

      def initialize: (untyped before_schema_data, untyped after_schema_data, ?::Hash[untyped, untyped] options) -> void
    end
  end
end

# Scope Rails
module R2OAS
  module Schema
    class Base < ::R2OAS::Base
    end
  end
end

module R2OAS
  module Schema
    class Builder
      @builder: untyped

      extend Forwardable

      def initialize: (?::Hash[untyped, untyped] options) -> void
    end
  end
end

module R2OAS
  module Schema
    class Cleaner
      @cleaner: untyped

      extend Forwardable

      def initialize: (?::Hash[untyped, untyped] options) -> void
    end
  end
end

# Scope Rails
module R2OAS
  module Schema
    class Editor < Base
      @editor: untyped

      @before_schema_data: untyped

      @schema_doc_from_local: untyped

      @running: untyped

      @chrome_user_data_dir: untyped

      @after_schema_data: untyped

      @save_mutex: untyped

      @save_thread: untyped

      @browser: untyped

      @container: untyped

      extend Forwardable

      TMP_FILE_NAME: "edited_schema"

      ALERT_TEXT: "Would you like to convert your JSON into YAML?"

      attr_accessor edited_schema: untyped

      def initialize: (untyped before_schema_data, untyped options) -> void

      def start: () -> untyped

      private

      attr_accessor unit_paths_file_path: untyped

      def setup_signal_traps: () -> untyped

      def cleanup: () -> untyped

      def process_after_close_browser: () -> (nil | untyped)

      # MEMO
      # TargetRubyVersion is 2.7 and there is a warning
      # Because it is necessary to support from ruby2.3 series where begin cannot be omitted
      # rubocop:disable Style/RedundantBegin
      def ensure_save_tmp_schema_file: () -> untyped

      def browser_exists?: () -> untyped

      def open_browser_and_set_schema: () -> untyped

      def chrome_options: (?headless: bool) -> untyped

      def get_local_storage: (untyped key) -> (nil | untyped)

      def set_local_storage: (untyped key, untyped value) -> untyped

      def wait_for_loaded: () -> untyped

      def container: () -> untyped
    end
  end
end

module R2OAS
  module Schema
    class Generator
      @generator: untyped

      extend Forwardable

      def initialize: (?::Hash[untyped, untyped] options) -> void
    end
  end
end

module R2OAS
  module Schema
    class PathItemFileManager
      @manager: untyped

      extend Forwardable

      def initialize: (untyped path, ?::Symbol path_type) -> void

      alias self.build self.new
    end
  end
end

module R2OAS
  module Schema
    class FileManager
      @manager: untyped

      extend Forwardable

      def initialize: (untyped path, ?::Symbol path_type) -> void

      alias self.build self.new
    end
  end
end

# Scope Rails
module R2OAS
  module Schema
    class Monitor < Base
      @before_schema_data: untyped

      @running: untyped

      @after_schema_data: untyped

      def initialize: (untyped before_schema_data, untyped options) -> void

      def start: () -> untyped

      private

      attr_accessor unit_paths_file_path: untyped

      def setup_signal_traps: () -> untyped

      def monitor_loop: () -> untyped

      def process_after_close_monitor: () -> untyped

      def fetch_after_schema_data: () -> untyped
    end
  end
end

module R2OAS
  module Schema
    class Squeezer
      @squeezer: untyped

      extend Forwardable

      def initialize: (untyped schema_data, ?::Hash[untyped, untyped] options) -> void
    end
  end
end

# Scope Rails
module R2OAS
  module Schema
    class UI < Base
      @ui: untyped

      @running: untyped

      @browser: untyped

      @container: untyped

      extend Forwardable

      alias swagger_json doc_save_file_path

      def initialize: (?::Hash[untyped, untyped] options) -> void

      def start: () -> untyped

      private

      attr_accessor unit_paths_file_path: untyped

      def setup_signal_traps: () -> untyped

      def cleanup: () -> untyped

      def open_browser: () -> untyped

      def wait_for_loaded: () -> untyped

      def container: () -> untyped
    end
  end
end

# Scope Rails
module R2OAS
  module Schema
    module V3
      class BaseAnalyzer < Base
        @type: untyped

        @before_schema_data: untyped

        @after_schema_data: untyped

        include Sortable

        def initialize: (untyped before_schema_data, untyped after_schema_data, ?::Hash[untyped, untyped] options) -> void

        def analyze_docs: () -> untyped

        def generate_from_existing_schema: () -> untyped

        private

        attr_accessor existing_schema_file_path: untyped

        attr_accessor type: untyped

        def create_after_schema_data: () -> untyped

        def create_after_schema_data_when_not_specify_path: () -> untyped

        def create_after_schema_data_when_specify_path: () -> untyped
      end
    end
  end
end

# Scope Rails
module R2OAS
  module Schema
    module V3
      module Components
        class ObjectAnalyzer < BaseAnalyzer
          @major_category: untyped

          @middle_category: untyped

          def initialize: (untyped before_schema_data, untyped after_schema_data, ?::Hash[untyped, untyped] options) -> void

          def analyze_docs: () -> untyped
        end
      end
    end
  end
end

# Scope Rails
module R2OAS
  module Schema
    module V3
      class ComponentsAnalyzer < BaseAnalyzer
        @options: untyped

        def initialize: (untyped before_schema_data, untyped after_schema_data, ?::Hash[untyped, untyped] options) -> void

        def analyze_docs: () -> untyped
      end
    end
  end
end

# Scope Rails
module R2OAS
  module Schema
    module V3
      class PathAnalyzer < BaseAnalyzer
        @tags: untyped

        VERB: ::Array["get" | "put" | "post" | "delete" | "options" | "head" | "patch" | "trace"]

        NOT_VERB: ::Array["$ref" | "summary" | "description" | "servers" | "parameters"]

        def initialize: (untyped before_schema_data, untyped after_schema_data, ?::Hash[untyped, untyped] options) -> void

        def analyze_docs: () -> untyped

        private

        def generate_tag_file?: () -> untyped

        def push_tags: (untyped tag_name) -> (untyped | nil)

        def unit_paths_data_group_by_tags: (untyped unit_paths_data) -> untyped

        def group_by_tags_when_verb: (untyped verb, untyped data_when_verb, untyped path, untyped result) -> untyped

        # The following pseudo tag names are after reservation
        # ・$ref
        # ・summary
        # ・description
        # ・servers
        # ・parameters
        def group_by_tags_when_not_verb: (untyped not_verb, untyped data_when_not_verb, untyped path, untyped result) -> untyped

        def save_each_tags: (untyped unit_paths_data) ?{ (untyped) -> untyped } -> untyped
      end
    end
  end
end

# Scope Rails
module R2OAS
  module Schema
    module V3
      class TagAnalyzer < BaseAnalyzer
        @file_manager: untyped

        @diff_manager: untyped

        def initialize: (untyped after_schema_data, ?::Hash[untyped, untyped] options) -> void

        def analyze_docs: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class Analyzer < BaseAnalyzer
        @path_analyzer: untyped

        @tag_analyzer: untyped

        @components_analyzer: untyped

        def initialize: (untyped before_schema_data, untyped after_schema_data, ?::Hash[untyped, untyped] options) -> void

        def analyze_docs: () -> untyped

        private

        def save_schema_when: (untyped schema_name) -> untyped
      end
    end
  end
end

# Scope Rails
module R2OAS
  module Schema
    module V3
      class Base < ::R2OAS::Schema::Base
        SUPPORT_COMPONENTS_OBJECTS: ::Array["schemas" | "requestBodies" | "securitySchemes" | "parameters" | "responses" | "examples" | "headers" | "links" | "callbacks"]

        def support_components_objects: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class BaseBuilder < Base
        @opts: untyped

        @glob_schema_paths: untyped

        @many_components_file_paths: untyped

        include Sortable

        def initialize: (?::Hash[untyped, untyped] opts) -> void

        private

        attr_accessor unit_paths_file_path: untyped

        attr_accessor skip_load_dot_paths: untyped

        attr_accessor opts: untyped

        attr_accessor use_plugin: untyped

        attr_accessor output: untyped

        alias use_plugin? use_plugin

        alias output? output

        def schema_file_do_not_exists?: () -> untyped

        def create_glob_schema_paths: () -> untyped

        def schema_files_paths: () -> untyped

        def many_paths_file_paths: () -> (::Array[untyped] | untyped)

        def many_components_file_paths: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class DocBuilder < BaseBuilder
        @pure_oas_doc: untyped

        @oas_doc: untyped

        attr_accessor oas_doc: untyped

        attr_accessor pure_oas_doc: untyped

        def initialize: (?::Hash[untyped, untyped] opts) -> void

        def build_docs: () -> untyped

        private

        def build_docs_from_schema_files: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class Builder < BaseBuilder
        @doc_builder: untyped

        extend Forwardable

        def initialize: (?::Hash[untyped, untyped] options) -> void

        def build_docs: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class BaseCleaner < Base
        def clean_docs: () ?{ (untyped) -> untyped } -> untyped

        private

        def many_paths_file_paths: () -> untyped

        def clean_target_files: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class ComponentsCleaner < BaseCleaner
        @components_file_paths: untyped

        @security_schemes_paths: untyped

        def initialize: (?::Hash[untyped, untyped] options) -> void

        def clean_docs: () -> untyped

        private

        def clean_target_files: () -> untyped

        def all_file_paths: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class Cleaner < BaseCleaner
        def clean_docs: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class BaseGenerator < Base
        @store: untyped

        @glob_schema_paths: untyped

        @many_components_file_paths: untyped

        @cache_docs: untyped

        include Sortable

        def initialize: (?::Hash[untyped, untyped] options) -> void

        private

        attr_accessor unit_paths_file_path: untyped

        attr_accessor skip_load_dot_paths: untyped

        attr_accessor is_create_cache: untyped

        attr_accessor store: untyped

        # Scope Rails
        def create_docs: () -> untyped

        def create_all_routes: () -> untyped

        def schema_file_do_not_exists?: () -> untyped

        def create_glob_schema_paths: () -> untyped

        def schema_files_paths: () -> untyped

        def many_paths_file_paths: () -> (::Array[untyped] | untyped)

        def many_components_file_paths: () -> untyped

        def exists_paths_files?: () -> untyped

        def cache_docs: () -> untyped

        def exists_cache?: () -> untyped

        def abs_cache_docs_path: () -> untyped

        def relative_cahe_docs_path: () -> ::String

        def unknown_paths_path: () -> ::String
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module Components
        class ObjectGenerator < BaseGenerator
          @major_category: untyped

          @middle_category: untyped

          @components_objects: untyped

          @glob_schema_paths: untyped

          def initialize: (?::Hash[untyped, untyped] schema_data, ?::Hash[untyped, untyped] options) -> void

          def generate_docs: () -> untyped

          private

          alias components_objects_files_paths schema_files_paths

          def generate_docs_from_routes_data: () -> untyped

          def process_when_generate_docs: () ?{ (untyped) -> untyped } -> untyped

          def create_glob_components_objects_paths: () -> untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module Components
        class RequestBodyGenerator < ObjectGenerator
          private

          # override
          def process_when_generate_docs: () ?{ (untyped) -> untyped } -> untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class ComponentsGenerator < BaseGenerator
        @components: untyped

        @options: untyped

        def initialize: (?::Hash[untyped, untyped] schema_data, ?::Hash[untyped, untyped] options) -> void

        def generate_docs: () -> untyped

        private

        def generator_class: (untyped object_name) -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class DocGenerator < BaseGenerator
        @schema_generator: untyped

        def initialize: (?::Hash[untyped, untyped] options) -> void

        def generate_docs: () -> untyped

        private

        def save_schemas_from_store: () -> untyped

        def save_diff_schemas_from: (untyped local_store) -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class PathGenerator < BaseGenerator
        @paths: untyped

        @glob_schema_paths: untyped

        def initialize: (?::Hash[untyped, untyped] schema_data, ?::Hash[untyped, untyped] options) -> void

        def generate_docs: () -> untyped

        private

        alias paths_files_paths schema_files_paths

        def generate_docs_from_routes_data: () -> untyped

        def process_when_generate_docs: () ?{ (untyped) -> untyped } -> untyped

        def create_glob_paths_paths: () -> (untyped | ::Array[::String])

        def unit_paths_data_group_by_tags: (untyped unit_paths_data) -> untyped

        def save_each_tags: (untyped unit_paths_data) ?{ (untyped) -> untyped } -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class SchemaGenerator < BaseGenerator
        @docs: untyped

        @options: untyped

        def initialize: (?::Hash[untyped, untyped] options) -> void

        def generate_docs: () -> untyped

        private

        def generate_docs_from_routes_data: () -> untyped

        def process_when_generate_docs: () ?{ (untyped) -> untyped } -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class Generator < BaseGenerator
        @doc_generator: untyped

        extend Forwardable

        def initialize: (?::Hash[untyped, untyped] options) -> void
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class BaseArrayDiffManager < BaseDiffManager
        @major_category: untyped

        @judge_key: untyped

        def initialize: (untyped before_schema_data, untyped after_schema_data) -> void

        def process_by_using_diff_data: () ?{ (untyped) -> untyped } -> untyped

        def after_target_data: () -> untyped

        private

        def schema_data_grouped_by_judge_key: (untyped arr) -> untyped

        def schema_data_at: (untyped data) -> ::Hash[untyped, untyped]

        def to_boolean: (untyped diff) -> (untyped | false)
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class BaseDiffManager < Base
        @before_schema_data: untyped

        @after_schema_data: untyped

        include Sortable

        def initialize: (untyped before_schema_data, untyped after_schema_data) -> void

        def process_by_using_diff_data: () -> untyped

        private

        def ensure_presence_or_blank: (untyped data) -> (untyped | ::Hash[untyped, untyped])
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class BaseHashDiffManager < BaseDiffManager
        @major_category: untyped

        @middle_category: untyped

        include Sortable

        def initialize: (untyped before_schema_data, untyped after_schema_data) -> void

        def process_by_using_diff_data: () ?{ (untyped, untyped, untyped, untyped, untyped) -> untyped } -> nil

        private

        def normalized: (untyped data) -> (untyped | ::Hash[untyped, ::Hash[untyped, ::Hash[untyped, untyped]]] | ::Hash[untyped, ::Hash[untyped, untyped]])

        def schema_data_at: (untyped data, untyped key) -> (::Hash[untyped, ::Hash[untyped, ::Hash[untyped, untyped]]] | ::Hash[untyped, ::Hash[untyped, untyped]])

        def sorted_target_data: (untyped data) -> untyped

        def to_boolean: (untyped diff, untyped target_name) -> (untyped | false)
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class ComponentsDiffManager < BaseHashDiffManager
        @major_category: untyped

        @middle_category: untyped

        @before_schema_data: untyped

        @after_schema_data: untyped

        def initialize: (untyped before_schema_data, untyped after_schema_data, ?::Hash[untyped, untyped] options) -> void
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class TagDiffManager < BaseArrayDiffManager
        @major_category: untyped

        @judge_key: untyped

        def initialize: (untyped before_schema_data, untyped after_schema_data) -> void
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class BaseFileManager < Base
        @ext_name: untyped

        @path_type: untyped

        @original_path: untyped

        @relative_save_file_path: untyped

        attr_accessor original_path: untyped

        # e.x.) openapi_path = "#/components/schemas/Account"
        def initialize: (untyped path, ?::Symbol path_type) -> void

        def delete: () -> untyped

        def save: (untyped data) -> untyped

        def save_after_deep_merge: (untyped data) -> untyped

        def save_file_path: (?type: ::Symbol) -> untyped

        def load_data: () -> untyped

        def descendants_paths: () -> ::Array[untyped]
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class ComponentsFileManager < IncludeRefBaseFileManager
        @path_type: untyped

        @original_path: untyped

        @recursive_search_class: untyped

        def initialize: (untyped path, ?::Symbol path_type) -> void

        def skip_save?: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class IncludeRefBaseFileManager < BaseFileManager
        @convert_underscore_to_slash: untyped

        @parent_save_file_paths: untyped

        @recursive_search_class: untyped

        REF: "$ref"

        def initialize: (untyped path, ?::Symbol path_type) -> void

        alias self.build self.new

        def descendants_paths: () -> untyped

        alias descendants_ref_paths descendants_paths

        private

        attr_accessor parent_save_file_paths: untyped

        attr_accessor recursive_search_class: untyped

        def deep_search_ref_recursive: (untyped yaml) { (?) -> untyped } -> untyped

        def process_deep_search_ref_recursive: (untyped ref_key_or_not, untyped ref_value_or_not) ?{ (untyped) -> untyped } -> (nil | untyped | untyped)
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class PathItemFileManager < IncludeRefBaseFileManager
        @recursive_search_class: untyped

        def initialize: (untyped path, ?::Symbol path_type) -> void

        def skip_save?: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class FileManager < BaseFileManager
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class PathnameManager < Base
        @ext_name: untyped

        @path_type: untyped

        @path: untyped

        # e.x.) path = "#/components/schemas/Account" (when path_type = :ref)
        def initialize: (untyped path, ?::Symbol path_type) -> void

        def object_type: () -> untyped

        def relative_save_file_path: () -> untyped

        private

        def normalized_about_path_type: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module FromFiles
        class BaseObject
          @opts: untyped

          @plugin_executor: untyped

          extend Forwardable

          def self.obj_store: () -> untyped

          def initialize: (?::Hash[untyped, untyped] opts) -> void

          def to_doc: () -> untyped

          private

          def obj_store: () -> untyped

          def set_root_doc: (untyped root_doc) -> untyped

          def root_doc: () -> untyped

          def set_components_name_list: (untyped root_doc) -> untyped

          def app_configuration_options: () -> untyped

          attr_accessor opts: untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module FromFiles
        module Components
          class RequestBodyObject < ::R2OAS::Schema::V3::FromFiles::BaseObject
            @doc: untyped

            @parent_ref: untyped

            @resolved_schema_name: untyped

            include ::R2OAS::Callable

            include DeepMethods

            def initialize: (untyped doc, untyped ref, untyped opts) -> void

            def to_doc: () -> untyped

            def resolve_dependencies!: () -> untyped

            def call_ref_path!: () -> untyped

            def schema_name: () -> untyped

            def ref_path: () -> ::String

            private

            def ref_dup: () -> untyped

            def reserved_schema_name_list: () -> untyped

            def create_child_ref: (untyped schema_name) -> untyped
          end
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module FromFiles
        module Components
          class SchemaObject < ::R2OAS::Schema::V3::FromFiles::BaseObject
            @doc: untyped

            @parent_ref: untyped

            @resolved_schema_name: untyped

            include ::R2OAS::Callable

            include DeepMethods

            def initialize: (untyped doc, untyped ref, untyped opts) -> void

            def to_doc: () -> untyped

            def resolve_dependencies!: () -> untyped

            def call_ref_path!: () -> untyped

            def schema_name: () -> untyped

            def ref_path: () -> ::String

            private

            def ref_dup: () -> untyped

            def reserved_schema_name_list: () -> untyped

            def create_child_ref: (untyped schema_name) -> untyped
          end
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module FromFiles
        class ComponentsObject < BaseObject
          @doc: untyped

          def initialize: (untyped doc, ?::Hash[untyped, untyped] opts) -> void

          def to_doc: () -> untyped

          private

          def create_doc: () -> untyped

          def create_components_schema_docs!: () -> untyped

          def create_components_request_body_docs!: () -> untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module FromFiles
        class ExternalDocumentObject < BaseObject
          @doc: untyped

          def initialize: (untyped doc, ?::Hash[untyped, untyped] opts) -> void

          def to_doc: () -> untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module FromFiles
        class InfoObject < BaseObject
          @doc: untyped

          def initialize: (untyped doc, ?::Hash[untyped, untyped] opts) -> void

          def to_doc: () -> untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module FromFiles
        class OpenapiObject < BaseObject
          @doc: untyped

          def initialize: (untyped doc, ?::Hash[untyped, untyped] opts) -> void

          def to_doc: () -> untyped

          private

          def info_doc: () -> untyped

          def paths_doc: () -> untyped

          def external_docs_doc: () -> untyped

          def components_doc: () -> untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module FromFiles
        class PathItemObject < BaseObject
          @doc: untyped

          @parent_ref: untyped

          include ::R2OAS::Callable

          include DeepMethods

          def initialize: (untyped doc, untyped ref, ?::Hash[untyped, untyped] opts) -> void

          def to_doc: () -> untyped

          # Breaking changes to @doc
          def resolve_dependencies!: () -> untyped

          def call_ref_path!: () -> untyped

          private

          def ref_dup: () -> untyped

          def resolve_dependencies_at_schema!: (untyped data, untyped verb, untyped data_when_verb, untyped local_ref_hash) -> untyped

          def resolve_dependencies_at_request_body!: (untyped data, untyped verb, untyped data_when_verb, untyped local_ref_hash) -> untyped

          def create_child_schema_ref: (untyped schema_name, untyped local_ref_hash) -> untyped

          def create_child_request_body_ref: (untyped schema_name, untyped local_ref_hash) -> untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module FromFiles
        class PathsObject < BaseObject
          @doc: untyped

          def initialize: (untyped doc, ?::Hash[untyped, untyped] opts) -> void

          def to_doc: () -> untyped

          private

          def create_doc: () -> untyped
        end
      end
    end
  end
end



module R2OAS
  module Schema
    module V3
      module FromFiles
        module DeepMethods
          def deep_replace!: (untyped data, untyped target) ?{ (untyped) -> untyped } -> (nil | untyped)
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module FromFiles
        class BaseRef
          @parent: untyped

          def pretty_print: (untyped q) -> untyped

          attr_reader parent: untyped

          def []=: (untyped key, untyped value) -> untyped

          def []: (untyped key) -> untyped

          def to_h: () -> untyped

          private

          # MEMO:
          # https://apidock.com/ruby/v1_9_3_392/PP/PPMethods/pp_hash
          def pp_hash: (untyped q, untyped obj) -> untyped

          def build: (untyped ref_or_data, ?::Hash[untyped, untyped] merge_data) -> untyped

          attr_writer parent: untyped

          def valid_keys: () -> untyped

          def writable_keys: () -> untyped
        end

        class PathRef < BaseRef
          VALID_KEYS: ::Array[:type | :path]

          def initialize: (untyped data) -> void

          private

          def valid_keys: () -> untyped

          def writable_keys: () -> ::Array[untyped]
        end

        module Components
          class SchemaRef < BaseRef
            READONLY_KEYS: ::Array[:type | :path | :parent_schema_name | :depth | :tag_name | :verb | :http_status | :from]

            WRITABLE_KEYS: ::Array[:schema_name]

            VALID_KEYS: untyped

            def initialize: (untyped ref_or_data) -> void

            private

            def valid_keys: () -> untyped

            def writable_keys: () -> untyped
          end

          class RequestBodyRef < BaseRef
            READONLY_KEYS: ::Array[:type | :path | :parent_schema_name | :depth | :tag_name | :verb | :from]

            WRITABLE_KEYS: ::Array[:schema_name]

            VALID_KEYS: untyped

            def initialize: (untyped ref_or_data) -> void

            private

            def valid_keys: () -> untyped

            def writable_keys: () -> untyped
          end
        end
      end
    end
  end
end



module R2OAS
  module Schema
    module V3
      class BaseObject
        @opts: untyped

        @plugin_executor: untyped

        @doc: untyped

        extend Forwardable

        def initialize: (?::Hash[untyped, untyped] opts) -> void

        def doc: () -> untyped

        def to_doc: () -> untyped

        private

        def app_configuration_options: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module Components
        class RequestBodyObject < R2OAS::Schema::V3::BaseObject
          @path_comp: untyped

          @path: untyped

          @route_data: untyped

          @verb: untyped

          @tag_name: untyped

          @schema_name: untyped

          # MEMO:
          # Allow primitive types that cannot be passed by reference to be passed by reference
          # This is Compromise
          @ref: untyped

          def initialize: (untyped route_data, untyped path, ?::Hash[untyped, untyped] opts) -> void

          def to_doc: () -> untyped

          def generate?: () -> untyped

          private

          def create_doc: () ?{ () -> untyped } -> untyped

          def _components_schema_name: () -> untyped

          def _components_request_body_name: () -> untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      module Components
        class SchemaObject < R2OAS::Schema::V3::BaseObject
          @path_comp: untyped

          @path: untyped

          @route_data: untyped

          @verb: untyped

          @tag_name: untyped

          @schema_name: untyped

          # MEMO:
          # Allow primitive types that cannot be passed by reference to be passed by reference
          # This is Compromise
          @ref: untyped

          def initialize: (untyped route_data, untyped path, ?::Hash[untyped, untyped] opts) -> void

          def to_doc: () -> untyped

          private

          def create_doc: () -> untyped

          def _components_schema_name: (untyped _http_status) -> untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class ComponentsObject < BaseObject
        @routes_data: untyped

        def initialize: (untyped routes_data, ?::Hash[untyped, untyped] opts) -> void

        def to_doc: () -> untyped

        def create_doc: () -> untyped

        private

        def create_doc_for_components_schemas!: () -> untyped

        def create_doc_for_components_request_bodies!: () -> untyped

        # e.x.)
        # [
        #  { path: "/tasks", data: {:verb=>"get", :path=>"/tasks", :tag_name=>"task" } },
        # ]
        def components_schema_docs: () -> untyped

        def components_request_body_docs: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class ExternalDocumentObject < BaseObject
        def to_doc: () -> untyped

        private

        def create_doc: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class InfoObject < BaseObject
        def to_doc: () -> untyped

        private

        def create_doc: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class OpenapiObject < BaseObject
        @routes_data: untyped

        @tags_data: untyped

        @schemas_data: untyped

        def initialize: (untyped routes_data, untyped tags_data, untyped schemas_data, ?::Hash[untyped, untyped] opts) -> void

        def to_doc: () -> untyped

        private

        def info_doc: () -> untyped

        def tags_doc: () -> untyped

        def paths_doc: () -> untyped

        def external_docs_doc: () -> untyped

        def servers_doc: () -> untyped

        def components_doc: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class PathItemObject < BaseObject
        @path_comp: untyped

        @path: untyped

        @route_data: untyped

        @verb: untyped

        @tag_name: untyped

        @schema_name: untyped

        @required_parameters: untyped

        @format_name: untyped

        @http_status_manager: untyped

        @components_schema_object: untyped

        @components_request_body_object: untyped

        extend Forwardable

        # reference
        # https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#path-item-object
        # Support Field Name: get, put, post, delete, patch
        SUPPORT_FIELD_NAME: ::Array["get" | "put" | "post" | "delete" | "patch"]

        def initialize: (untyped route_data, untyped path, ?::Hash[untyped, untyped] opts) -> void

        def to_doc: () -> untyped

        def create_doc: () -> untyped

        private

        def data_when_verb: () -> untyped

        def responses_when_http_status: () -> untyped

        def _components_schema_name: (untyped http_status) -> untyped

        def _components_request_body_name: () -> untyped

        def create_format_name: () -> untyped

        def attach_request_body!: (untyped schema) -> untyped

        def attach_media_type!: (untyped schema) -> untyped

        def attach_parameters!: (untyped schema) -> untyped

        def support_field_name?: () -> (untyped | nil)

        class HttpStatusManager
          @path_comp: untyped

          @verb: untyped

          @http_statuses_when_http_method: untyped

          def initialize: (untyped path, untyped verb, untyped http_statuses_when_http_method) -> void

          def http_statuses: () -> untyped
        end
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class PathsObject < BaseObject
        @routes_data: untyped

        def initialize: (untyped routes_data, ?::Hash[untyped, untyped] opts) -> void

        def to_doc: () -> untyped

        def create_doc: () -> untyped

        private

        def path_item_docs: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class ServerObject < BaseObject
        def to_doc: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class TagObject < BaseObject
        @tags_data: untyped

        def initialize: (untyped tags_data, ?::Hash[untyped, untyped] opts) -> void

        def to_doc: () -> untyped

        private

        def create_doc: (untyped tag_name) -> { "name" => untyped, "description" => ::String, "externalDocs" => { "description" => "description", "url" => "url" } }
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class Store
        self.@instance: untyped

        @data: untyped

        @root_doc: untyped

        @components_schema_name_list: untyped

        @appended_components_schema_name_list: untyped

        @components_request_body_name_list: untyped

        @appended_components_request_body_name_list: untyped

        attr_accessor root_doc: untyped

        attr_accessor components_schema_name_list: untyped

        attr_accessor appended_components_schema_name_list: untyped

        attr_accessor components_request_body_name_list: untyped

        attr_accessor appended_components_request_body_name_list: untyped

        def initialize: (?::Symbol type) -> void

        def add: (untyped obj_type, untyped key, untyped value) -> untyped

        def gets: (untyped obj_type) -> (untyped | ::Array[untyped])

        extend Forwardable

        def self.create: (?::Symbol type) -> untyped

        private

        def self.instance: (untyped type) -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class BaseSqueezer < Base
        @schema_data: untyped

        @tag_names: untyped

        def initialize: (untyped schema_data, ?::Hash[untyped, untyped] options) -> void

        def squeeze_docs: () -> untyped

        private

        attr_accessor many_paths_file_paths: untyped

        def create_tag_names: () -> untyped
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class PathSqueezer < BaseSqueezer
        VERB: ::Array["get" | "put" | "post" | "delete" | "options" | "head" | "patch" | "trace"]

        NOT_VERB: ::Array["$ref" | "summary" | "description" | "servers" | "parameters"]

        def squeeze_docs: () -> { "paths" => untyped }
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class TagSqueezer < BaseSqueezer
        def squeeze_docs: () -> { "tags" => untyped }
      end
    end
  end
end

module R2OAS
  module Schema
    module V3
      class Squeezer < BaseSqueezer
        def squeeze_docs: () -> untyped
      end
    end
  end
end



module R2OAS
  module Callable
    def deep_call: (untyped data, untyped target, untyped callback) -> untyped
  end
end

module R2OAS
  module Sortable
    def deep_sort: (untyped data, untyped target) -> untyped
  end
end

module R2OAS
  class Store
    self.@instance: untyped

    @data: untyped

    @type: untyped

    attr_accessor data: untyped

    def initialize: (untyped type, ?::Hash[untyped, untyped] data) -> void

    def add: (untyped key, untyped value) -> untyped

    def save: () { (untyped) -> untyped } -> untyped

    def dup_slice: (*untyped sha1s) -> untyped

    def checksum?: () -> untyped

    def key?: (untyped key) -> untyped

    def exists?: () -> untyped

    def diff_from: (untyped local_store) ?{ (untyped) -> untyped } -> untyped

    private

    def calc_sha1: (untyped key, untyped value) -> untyped

    def values: () -> untyped

    def adjust: (untyped hash, untyped direct) -> untyped

    extend Forwardable

    def self.create: (?::Symbol type) -> untyped

    def self.instance: (untyped type) -> untyped
  end
end

# copy from https://github.com/rails/rails/blob/master/activesupport/lib/active_support/deprecation/instance_delegator.rb
module R2OAS
  class Deprecation
    module InstanceDelegator
      # MEMO:
      # base must be singleton class
      def self.included: (untyped base) -> untyped

      module ClassMethods
        # override Module#include
        def include: (untyped included_module) -> untyped

        def method_added: (untyped method_name) -> untyped
      end

      module OverrideDelegators
        def warn: (?untyped? message, ?untyped? callstack) -> untyped

        alias will_remove warn
      end
    end
  end
end

# MEMO:
# copy from https://github.com/rails/rails/blob/master/activesupport/lib/active_support/deprecation/reporting.rb
module R2OAS
  class Deprecation
    module Reporting
      attr_accessor silenced: untyped

      attr_accessor gem_name: untyped

      FILE_LINE_METHOD_REGEXP: ::Regexp

      R2OAS_GEM_ROOT: ::String

      def warn: (?untyped? message, ?untyped? callstack) -> (nil | untyped)

      alias will_remove warn

      def silence: () ?{ () -> untyped } -> untyped

      private

      def deprecation_message: (untyped callstack, ?untyped? message) -> ::String

      def deprecation_caller_message: (untyped callstack) -> untyped

      def extract_callstack: (untyped callstack) -> (untyped | ::Array[untyped])

      # e.g.)
      # callback = /path/to/file.rb:274:in `require'
      #
      # file = /path/to/file.rb
      # line = 274
      # method = require
      def _extract_callstack: (untyped _callback) -> untyped

      # MEMO:
      # see https://docs.ruby-lang.org/ja/latest/class/RbConfig.html#C_-C-O-N-F-I-G
      def ignored_callstack: (untyped path) -> untyped
    end
  end
end

module R2OAS
  class Deprecation
    include Singleton

    # Be sure to follow the Singleton module
    include InstanceDelegator

    include Behavior

    include Reporting

    # The version number in which the deprecated behavior will be removed, by default.
    attr_accessor deprecation_horizon: untyped

    def initialize: (?::String deprecation_horizon, ?::String gem_name) -> void
  end
end

module R2OAS
  class Task < ::Rails::Railtie
  end
end

# Scope Rails
module R2OAS
  module TaskLogging
    def task: (*untyped) ?{ (?) -> untyped } -> untyped

    private

    def start: (?::String initial) { () -> untyped } -> untyped

    def logger: () -> untyped

    def set_debug_level: () -> untyped

    def debug_log: (untyped task, untyped message) -> (untyped | nil)
  end
end

module R2OAS
  VERSION: "0.5.0"
end

module R2OAS
  extend Configuration

  module Schema
  end
end

