# MEMO:
# copy from https://github.com/rails/rails/blob/master/activesupport/lib/active_support/deprecation/behaviors.rb
module R2OAS
  class Deprecation
    class DeprecationError < StandardError
    end

    DEFAULT_BEHAVIORS: { stderr: untyped }

    module Behavior
      @behavior: untyped

      def behavior: () -> untyped
    end
  end
end
