module R2OAS
  module Schema
    module V3
      module FromFiles
        class InfoObject < BaseObject
          @doc: untyped

          def initialize: (untyped doc, ?::Hash[untyped, untyped] opts) -> void

          def to_doc: () -> untyped
        end
      end
    end
  end
end
